name: Build and Run Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask_app_image .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name flask_app_container flask_app_image
          sleep 5  # Wait for the Flask app to start

      - name: Test Flask API
        run: |
          response=$(curl -X POST http://127.0.0.1:5000/your-endpoint -d '{"key": "value"}' -H 'Content-Type: application/json')
          echo "Response: $response"

      - name: Clean up
        run: |
          docker stop flask_app_container
          docker rm flask_app_container
