name: build-test-deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Run Flask server in the background
      - name: Start Flask server
        run: |
          nohup flask run &

      # Test API endpoints (you can use curl or any testing script)
      - name: Test API
        run: |
          sleep 5  # Wait for server to start
          curl -X POST http://127.0.0.1:5000/your-endpoint -d '{"data":"value"}' -H 'Content-Type: application/json'
      
      # Continue with other steps
      - name: Additional steps
        run: |
          echo "Perform additional build or test steps here"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Add deployment steps here
      - name: Deploy to production
        run: |
          echo "Add deployment commands here"
