name: build-test-deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      flask:
        image: pragnakalpdev51/actions-learning-pathway_demo:latest
        options: >-
          --entrypoint "flask run --host=0.0.0.0"
        ports:
          - 5000:5000
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Wait for Flask service to start
      - name: Wait for Flask to be ready
        run: |
          sleep 10  # Adjust this based on how long your Flask app takes to start

      # Test the Flask API
      - name: Test API endpoints
        run: |
          curl http://localhost:5000/your-endpoint

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Deployment steps here
      - name: Deploy to production
        run: |
          echo "Add deployment commands here"
