name: build-test-deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Flask App in Docker
        uses: pragnakalpdev51/actions-learning-pathway_demo@main
        with:
          flask-version: '3.x'

      # Run your Flask app in the background
      - name: Start Flask server
        run: |
          nohup flask run &

      # Install dependencies for testing (e.g., requests, pytest)
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Test the Flask API
      - name: Test API
        run: |
          python -m pytest tests/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Deploy the Flask app (you need to specify your deployment steps)
      # - name: Deploy to server
      #   run: |
      #     # Example command, replace with actual deployment steps
      #     scp -r * user@yourserver.com:/path/to/deploy/
