# name: Run Hello Script and Test

# on:
#   push:
#     branches:
#       - main  

# jobs:
#   run:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.8'  

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install flask  # Install Flask if you need it for your app

#       - name: Run hello.py
#         run: |
#           nohup python new.py &  # Run the Flask app in the background
#           sleep 10  # Wait for the server to start

#       # - name: Send POST request
#       #   run: |
#       #     payload='{"data":"Hello"}'  # Replace this with your dynamic data
#       #     echo "Sending payload: $payload"  # Print the payload
#       #     curl -X POST https://28d1-2401-4900-8899-e44d-d205-1008-1294-cfaf.ngrok-free.app/ \
#       #     -d "$payload" -H 'Content-Type: application/json'
name: Run Hello Script

on:
  push:
    branches:
      - main  # Change to your default branch if it's not main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have dependencies, install them here, e.g.:
          # pip install -r requirements.txt

      - name: Run hello.py
        run: python hello.py
