name: CI/CD for Flask App

on:
  push:
    branches:
      - main  # Change this to your main branch if different
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask_app_image .

      - name: Save Docker image as artifact
        run: |
          docker save flask_app_image | gzip > flask_app_image.tar.gz
      - name: upload docker
        uses: actions/upload-artifact@v3
        with:
          name: flask_app_image
          path: flask_app_image.tar.gz

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: flask_app_image

      - name: Load Docker image
        run: gunzip -c flask_app_image.tar.gz | docker load

      - name: Run Docker container for testing
        run: |
          docker run -d -p 5000:5000 --name flask_app_container flask_app_image
          sleep 5  # Wait for the Flask app to start

      - name: Test Flask API
        run: |
          curl -X POST http://127.0.0.1:5000/ -d '{"data":"value"}' -H 'Content-Type: application/json'

      - name: Clean up
        run: |
          docker stop flask_app_container
          docker rm flask_app_container

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: flask_app_image

      - name: Load Docker image
        run: gunzip -c flask_app_image.tar.gz | docker load

      - name: Run Docker container in production
        run: |
          docker run -d -p 5000:5000 --name flask_app_container flask_app_image
          sleep 5  # Wait for the Flask app to start
