name: Run Hello Script

on:
  push:
    branches:
      - main  # Change to your default branch if it's not main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          # If you have dependencies, install them here, e.g.:
          # pip install -r requirements.txt

      - name: Run hello.py
        run: python hello.py
